### ISSUE TITLE
Button & Card malfunction

### ISSUE THREAD

**Issue by Melphios** [nomadjimbob/mikioplugin#12]
Hi,
First thanks for your great job.
I'm facing some problems with cards and buttons, I can't get outlined button and button in cards with good ratio to work.
I've made test with given examples in the wiki
```
====== Example Syntax ======


<button primary>Primary</button>
<button secondary>Secondary</button>
<button success>Success</button>
<button danger>Danger</button>
<button warning>Warning</button>
<button info>Info</button>
<button light>Light</button>
<button dark>Dark</button>
<button link>Link</button>

====== Outline ======

<button outline-primary>Primary</button>
<button outline-secondary>Secondary</button>
<button outline-success>Success</button>
<button outline-danger>Danger</button>
<button outline-warning>Warning</button>
<button outline-info>Info</button>
<button outline-light>Light</button>
<button outline-dark>Dark</button>

====== Card ======

<card header="Featured" footer="2 days ago" title="Special title treatment" text-center>
With supporting text below as a natural lead-in to additional content.

<button>Go somewhere</button>
</card>
```
And it give me this result
![Screenshot_20210804_152805](https://user-images.githubusercontent.com/88441373/128189263-05bc6ca1-c5aa-435c-9cdc-acea7ff7f636.png)

If someone knows what should I do to correct this, he's welcome :)

**Comment by nomadjimbob** [comment]
Thanks Melphios for raising these issues.

I have fixed the outline style issue in version 2010-08-10 which will be released shortly. The button in a card is working as expected, however the wiki is outdated on how to use buttons inside a card. I will update it ASAP.

All elements inside a card have a width of 100% due to the way flexbox CSS works. You can get around this in your case by setting the button alignment to centre and giving it a width such as:

`<button align-center width=10rem>Go somewhere</button>`

If you want to have 2 buttons side by side, you would need to enclose them in a <row> and <col> tags and set the alignments to your preferred.

Hope that makes sense

**Comment by nomadjimbob** [comment]
Wiki updated

**Comment by Melphios** [comment]
Thanks for your answer,
At this moment I'm with very limited access to Internet, so I couldn't thank you before  :) 
But all work fine.
